### ISSUE TITLE
No download button in `https://elixir.ut.ee/eqtl/?gene_name=KRAS`

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#10]
I am trying to download data from elixir, however, it looks no download button to let user download it.

https://elixir.ut.ee/eqtl/?gene_name=KRAS

Any comments? 

Thanks.

**Comment by kauralasoo** [comment]
Yes, there's currently no download option in the credible set browser, but you can download the underlying raw data from our FTP: ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/credible_sets/
