### ISSUE TITLE
multiple different beta for same GenexSNP pair

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#11]
I notice the several different beta for eQTL between ENSG00000008128 and rs28544273. How to understand it? Thanks. 

<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/sguo2/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/sguo2/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>

molecular_trait_id | chromosome | position | ref | alt | variant | ma_samples | maf | pvalue | beta | se | type | ac | an | r2 | molecular_trait_object_id | gene_id | median_tpm | rsid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ENSG00000008128.grp_1.contained.ENST00000356200 | 1 | 815963 | T | A | chr1_815963_T_A | 163 | 0.144112 | 0.84493 | 0.0240479 | 0.122892 | SNP | 178 | 1138 | 0.45909 | ENSG00000008128.contained | ENSG00000008128 | 5.626 | rs28544273
ENSG00000008128.grp_1.contained.ENST00000356937 | 1 | 815963 | T | A | chr1_815963_T_A | 163 | 0.144112 | 0.777514 | -0.0337367 | 0.119338 | SNP | 178 | 1138 | 0.45909 | ENSG00000008128.contained | ENSG00000008128 | 5.626 | rs28544273
ENSG00000008128.grp_1.contained.ENST00000358779 | 1 | 815963 | T | A | chr1_815963_T_A | 163 | 0.144112 | 0.135332 | 0.178658 | 0.119457 | SNP | 178 | 1138 | 0.45909 | ENSG00000008128.contained | ENSG00000008128 | 5.626 | rs28544273
ENSG00000008128.grp_1.contained.ENST00000378633 | 1 | 815963 | T | A | chr1_815963_T_A | 163 | 0.144112 | 0.355045 | -0.114477 | 0.123676 | SNP | 178 | 1138 | 0.45909 | ENSG00000008128.contained | ENSG00000008128 | 5.626 | rs28544273

**Comment by kauralasoo** [comment]
These are different alternative splicing events within the same gene. Although the gene ids are the same, the molecular_trait_ids's are not, because the transcript ids (ENST*) are different. See the txrevise paper (https://elifesciences.org/articles/41673v1) to learn more how these events are constructed.
