### ISSUE TITLE
conflicted results within same file `Quach_2016_txrev_monocyte_R848`

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#14]
Dear Sir/Madam, 

I observed same conflicted result. take the following as example, beta=-0.200425 and beta=0.200425 are showed for same SNP-Gene pair. How to understand it. 

```
[sguo2@login01 eqtlcatalog]$ tabix Quach_2016_txrev_monocyte_R848.all.tsv.gz.gz 16:28506388-28506388 | grep 0.044129
16      28506388        16-28506388-T-C -0.200425       0.0441293       1.02893e-05     ENSG00000197272 rs26528
16      28506388        16-28506388-T-C 0.200425        0.0441293       1.02893e-05     ENSG00000197272 rs26528
```
Thanks. 

Shicheng

**Comment by Shicheng-Guo** [comment]
Here is the what I find in the raw data: 

```
(base) [sguo2@login01 raw]$ zcat Quach_2016_txrev_monocyte_R848.all.tsv.gz | grep 28506388 | grep 0.0441293

ENSG00000197272.grp_1.upstream.ENST00000356897  16      28506388        T       C       chr16_28506388_T_C      125     0.418848        1.02893e-05     -0.200425       0.0441293       SNP     160     382     0.99982 ENSG00000197272.upstream     ENSG00000197272 173.295 rs26528
ENSG00000197272.grp_1.upstream.ENST00000568075  16      28506388        T       C       chr16_28506388_T_C      125     0.418848        1.02893e-05     0.200425        0.0441293       SNP     160     382     0.99982 ENSG00000197272.upstream     ENSG00000197272 173.295 rs26528
```

**Comment by kauralasoo** [comment]
Hi Shicheng,

These are QTL results from txrevise analysis. The two rows have different molecular_trait_ids (first column) which correspond to different transcripts of the same gene. If the relative expression ("usage") of one transcript of a gene goes up then the some of the other ones need to go down ( because they need to sum up to 1). Thus, it is expected to see that the same variant has opposing effects on the relative expression of different transcripts of the same gene. See the txrevise paper for more details: https://elifesciences.org/articles/41673.

Best,
Kaur

**Comment by Shicheng-Guo** [comment]
if the beta is relative to specific gene, that make sense. However, it is still quite difficult to understand why the abs(beta), se, pvalue, nsnp,..., all these are same. I will read the paper you mentioned. Thank you for your response Kaur!! Shicheng

**Comment by Shicheng-Guo** [comment]
Dear Kaurl, 

Do we have gene-level eQTL-summary statistics?  Relative usage concept maybe hard to be accepted since I think we are always want to know the absolute eQTL, not relative eQTL. From biology perspective, REF/ALT allele can increase/decrease both transcript.  

Thanks. 

Shicheng

**Comment by Shicheng-Guo** [comment]
Dear Kaur, 

It looks among 250 tissue/cell eQTL summary statistics, about 46 are from txrevise analysis while other use other approach correct? This number is consistent/closed to the number N=18+29=47 mentioned in colocalisation section in preprint paper. 

Shicheng

"The same colocalisation was also detected by transcript usage in 18/95 datasets and by txrevise in 29/95 datasets"
