### ISSUE TITLE
expression data of eQTL catalog

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#16]
I am wondering whether expression data matrix (TPM or FPKM matrix) are available? 
Thanks
Shicheng

**Comment by kauralasoo** [comment]
RNA-seq count matrices from release 3 are here:
https://zenodo.org/record/4678936#.YYmoO71Bw_8

Microarray matrices are here:
https://zenodo.org/record/3565554#.YYmodr1Bw_8

**Comment by Shicheng-Guo** [comment]
Great. Thanks Kaur!!
