### ISSUE TITLE
Normal/healthy tissues/dataset in eQTL-catalog as well as scRNA-seq dataset

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#17]
Hi Kaur, 

I want to confirm all the samples/dataset in eQTL-catalog are normal/heathy tissues, correct? Is there any disease-related RNA-seq data is included? meanwhile, is there any scRNA-seq data are included? 

Thanks

Shicheng

**Comment by kauralasoo** [comment]
Most should be from normal/healthy tissues, but I think that ROSMAP also has some disease samples. You can check the original publications if you want the make sure. No scRNA-seq data yet, but we hope to include some in the near future.
