### ISSUE TITLE
dominant and recessive model for eQTL

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#18]
Hi Kaur, 
do we have the dominant and recessive model results for eQTL?
Thanks
Shicheng

**Comment by kauralasoo** [comment]
Do you have an example where dominant or recessive model would make sense for cis-eQTLs? Cis-eQTLs, by definition, only influence the expression of the copy of the gene that is on the same physical chromosome with the effect allele. Dominant and recessive models could make sense for trans-eQTLs, but we currently do not have any trans-eQTL summary statistics.
