### ISSUE TITLE
Unable to ftp get the tx (transcription usage) data

### ISSUE THREAD

**Issue by AMCalejandro** [eQTL-Catalogue/eQTL-Catalogue-resources#24]
Hi,

I am unable to get the transcription usage data. When use the function provided with the tabix tutorial, all the data frames are empty.

At the beginning I thought it had to do with the gene filtering. I assumed we had to use transcript names instead of ENSEMBL GENE IDs.
However, I removed the filter according to gene/transcript name, and I tried to import the tx data for a random dataset.

Still I couldn't
```

import_eQTLCatalogue <- function(ftp_path, region, column_names, verbose = TRUE){
  
  if(verbose){
    print(ftp_path)
  }
  
  #Fetch summary statistics with seqminer
  fetch_table = seqminer::tabix.read.table(tabixFile = ftp_path, tabixRange = region, stringsAsFactors = FALSE) %>%
    dplyr::as_tibble()
  colnames(fetch_table) = column_names
  
  #Remove rsid duplicates and multi-allelic variant
  summary_stats = fetch_table %>%
    dplyr::select(-rsid) %>% 
    dplyr::distinct() %>% #rsid duplicates
    dplyr::mutate(id = paste(chromosome, position, sep = ":")) %>% 
    dplyr::group_by(id) %>% 
    dplyr::mutate(row_count = n()) %>% dplyr::ungroup() %>% 
    dplyr::filter(row_count == 1) #Multialllics
}

```
<pre>&gt; ftp_path_list$Alasoo_2018_macrophage_Salmonella
[1] &quot;ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/tx/Alasoo_2018_tx_macrophage_Salmonella.all.tsv.gz&quot;
&gt; data = import_eQTLCatalogue(ftp_path_list$Alasoo_2018_macrophage_Salmonella, region = region, column_names= column_names)
[1] &quot;ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/csv/Alasoo_2018/tx/Alasoo_2018_tx_macrophage_Salmonella.all.tsv.gz&quot;
&gt; data
<font color="#949494"># A tibble: 0 × 20</font>
<font color="#949494"># … with 20 variables: molecular_trait_id &lt;chr&gt;, chromosome &lt;int&gt;,</font>
<font color="#949494">#   position &lt;int&gt;, ref &lt;chr&gt;, alt &lt;chr&gt;, variant &lt;chr&gt;, ma_samples &lt;int&gt;,</font>
<font color="#949494">#   maf &lt;dbl&gt;, pvalue &lt;dbl&gt;, beta &lt;dbl&gt;, se &lt;dbl&gt;, type &lt;chr&gt;, ac &lt;int&gt;,</font>
<font color="#949494">#   an &lt;int&gt;, r2 &lt;dbl&gt;, molecular_trait_object_id &lt;chr&gt;, gene_id &lt;chr&gt;,</font>
<font color="#949494">#   median_tpm &lt;dbl&gt;, id &lt;chr&gt;, row_count &lt;int&gt;</font>
&gt; 
</pre>

**Comment by kauralasoo** [comment]
We have updated the files on the FTP a few days ago. Can you try it again?

If the R function still does not work, can you try to use tabix from the command line just to see that it works?
