### ISSUE TITLE
10 sec time out when accessing tabix data via ftp

### ISSUE THREAD

**Issue by AMCalejandro** [eQTL-Catalogue/eQTL-Catalogue-resources#25]
Hi,

I am just running coloc against gw eQTL datasets, and after performing a few runs, I get a 10sex time out error:

```
> column_names = colnames(readr::read_tsv(myTissue_metadata$ftp_path, n_max = 1))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'colnames': Timeout was reached: [ftp.ebi.ac.uk] Connection timed out after 10001 milliseconds
```

I wonder if there is some sort of annoying cap that prevents me from qurying ftp data daily as much as I can ?

**Comment by kauralasoo** [comment]
I think the fundamental issues is that the EBI firewall sees tabix requests over FTP as incomplete downloads. If these occur 'too often' then the firewall algorithm thinks that there is a denial-of-service (DoS) attack and either blacklists the IP address or enforces a timeout. We have discussed this with the EBI team and unfortunately there is no good solution. Enforcing an timeout of your own (e.g. making at most one request every few seconds) might help, but is not guaranteed to work. 

If you can, you might want to download the full summary statistics files and perform tabix queries locally. The firewall likes complete downloads much more than incomplete downloads.

In the long term, the best option might be switch to our REST API, but the REST API is currently undergoing major revisions and the data on there is outdated (from release 3). We hope to fix the API by the end of the year.
