### ISSUE TITLE
GTEx sample size in tabix_ftp_paths.tsv is different from gtexportal

### ISSUE THREAD

**Issue by mhaiyue** [eQTL-Catalogue/eQTL-Catalogue-resources#26]
Hi there,

I notice that the GTEx sample size in [tabix/tabix_ftp_paths.tsv](https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tabix/tabix_ftp_paths.tsv) is different from gtexportal.

Take muscle tissue as an example, sample size here is 410, but on [GTExportal](https://gtexportal.org/home/tissueSummaryPage) it's 706(RNASeq and Genotyped samples) or 803(RNASeq samples) .

What's happening here?  Is the GTEx sample_size from tabix/tabix_ftp_paths.tsv GTEx V7 version?

**Comment by kauralasoo** [comment]
Thanks for reporting it! These sample size are indeed from GTEx V7, but the linked summary statistics are from GTEx v8. We will fix the sample sizes and let you know when it's done. In the meantime you can extract sample sizes from the `an` column in summary statistics files (n = an/2 for chromosomes 1:22, X behaves slightly differently in males).

**Comment by kauralasoo** [comment]
The sample sizes in [tabix/tabix_ftp_paths.tsv](https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tabix/tabix_ftp_paths.tsv) have now been fixed in release 6.

Best,
Kaur
