### ISSUE TITLE
eQTL_Catalogue.fetch:  pre-filter by pvalue?

### ISSUE THREAD

**Issue by paul-shannon** [eQTL-Catalogue/eQTL-Catalogue-resources#27]
Thank you for this fine package!

May I request an additional filtering parameter to eQTL_Catalogue.fetch?  In addition to chrom, bp_lower and bp_upper?  

 Could you add ```pvalue```?   For my use case, this would dramatically reduce the size of the table returned by REST, by (in one current example) 98%!

**Comment by kauralasoo** [comment]
We have now completely re-written our REST API. 

See the documentation here:
https://www.ebi.ac.uk/eqtl/api/docs

And a tutorial:
https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/master/tutorials/API_v2/eQTL_API_tutorial.md

You should now be able to filter on nlog10p.

Best,
Kaur
