### ISSUE TITLE
Human Kidney eQTL Atlas

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#28]
Dear Team,

I am trying to check whether Human Kidney eQTL Atlas is included in the project or not? 

https://susztaklab.com/Kidney_eQTL/download.php

Thanks. 

Shicheng

**Comment by kauralasoo** [comment]
Unfortunately it is not. The genotype data from the Human Kidney eQTL Atlas is not available for third party researchers and so we are unable to process the data for the eQTL Catalogue.
