### ISSUE TITLE
Return lbf_variable for use with coloc v5

### ISSUE THREAD

**Issue by jdblischak** [eQTL-Catalogue/eQTL-Catalogue-resources#29]
First, thanks for this amazing resource!

I am interested in performing colocalization with the GTEx eQTLs with support for multiple causal variants. This requires first fine-mapping with SuSiE. Since you have already fine-mapped all the GTEx eQTLs with SuSiE, I was hoping to directly use your results for colocalization. Unfortunately, `coloc_bf_bf()` requires the output `lbf_variable` from the SuSiE object, and your current tables do not include these [columns](https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/d018846bd203c50852ca3a1341f755685cf88640/tabix/Columns.md#column-names-of-the-fine-mapped-credible-set-files-from-susie).

I went to the source code in [run_susie.R](https://github.com/eQTL-Catalogue/qtlmap/blob/752a42eb0c5b7ef26a4bcf97faebe2b2067f3e44/bin/run_susie.R) to attempt to modify it, but it appears that you are already exporting `lbf_variable` to support this use case (PR https://github.com/eQTL-Catalogue/qtlmap/pull/11). Since you are fine-mapping with `L = 10`, I would expect the results to include the columns `lbf_variable1` to `lbf_variable10`.

Is there any way I can access the results files that include these columns?

**Comment by kauralasoo** [comment]
Hi John,

We are currently in the middle of generating these lbf_variable outputs for all quantification methods, including Leafcutter that was currently missing, and hope to publish these results towards the end of the year with the next eQTL Catalogue release. What's your timeline? We do have some preliminary results for gene expression only that have not been released publicly yet. Feel free to reach out to me by email via kaur.alasoo [at] ut .ee.

**Comment by jdblischak** [comment]
@kauralasoo I'm looking forward to the next public release. Thanks!
