### ISSUE TITLE
Inconsistency between new data and the ones in manuscript_plot_updates branch

### ISSUE THREAD

**Issue by Ojami** [eQTL-Catalogue/eQTL-Catalogue-resources#33]
Hi,

I was wondering why there are discrepancies between summary stats in the master branch and the old branch (manuscript_plot_updates )?
As an example, summary stats here `ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/sumstats/QTS000015/QTD000321/QTD000321.all.tsv.gz` and here `ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/imported/GTEx_V8/ge/Small_Intestine_Terminal_Ileum.tsv.gz`, are quite different. 

Thanks in advance
Best/Oveis

**Comment by kauralasoo** [comment]
Hi Oveis,

All of the summary stats under ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/sumstats/ are from release 6, described here:
https://www.ebi.ac.uk/eqtl/Release_notes/

The files under ftp://ftp.ebi.ac.uk/pub/databases/spot/eQTL/imported/GTEx_V8/ are from the original GTEx analysis, not from our uniform re-analysis. Due to differences in methodology, some differences in summary stats are expected.

Best,
Kaur

**Comment by Ojami** [comment]
Hi Kaur,

Thanks for clearing that up. But I also see some differences between the _old_ processed (i.e. not imported) sum stats under `https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/manuscript_plot_updates/tabix/tabix_ftp_paths.tsv` (.e.g `GTEx/GTEx_ge_adipose_subcutaneous.all.tsv.gz`) and new ones. Is this difference because of the updated workflow? 

Since we have done few colocalizations using the original _old_ processed sum stats (`https://github.com/eQTL-Catalogue/eQTL-Catalogue-resources/blob/manuscript_plot_updates/tabix/tabix_ftp_paths.tsv`), I was wondering how much difference one could expect to get in terms of fine-mapping or colocalization?

Thanks!
Best/Oveis

**Comment by kauralasoo** [comment]
Hi Oveis,
I think most differences between release 5 and release 6 should be minimal, especially for gene expression quantification results. We did re-align all of the data and used updated reference transcriptome annotations, but the number of samples and covariates included in the analysis stayed the same.

Best,
Kaur

**Comment by Ojami** [comment]
That's great! 👍 

Best/Oveis
