### ISSUE TITLE
how do you get SORT1 position is 109274570

### ISSUE THREAD

**Issue by crhywun** [eQTL-Catalogue/eQTL-Catalogue-resources#37]
I searched ncbi the position is ch1 109,852,197-109,940,540 in GRCh37
ch1 109,309,575-109,397,918 in GRCh38.
I also search ensembl position is ch1: 109,309,568-109,397,918 in GRCh38

**Comment by kauralasoo** [comment]
109274570 is the position of the eQTL variant associated with SORT1 expression, not the position of the SORT1 gene. Many eQTL variants reside outside the genes that they regulate. However, in this case the likely causal variant is probably chr1_109274968_G_T, which is also not inside the gene body: https://www.nature.com/articles/nature09266.

We should probably modify the tutorial to use the chr1_109274968_G_T variant.
