### ISSUE TITLE
Potential misspecification of tissue label in meta data for Schmiedel et al data

### ISSUE THREAD

**Issue by VitorAguiar** [eQTL-Catalogue/eQTL-Catalogue-resources#39]
Hi,

I have a clarifying question about the meta data for dataset QTS000026 "Schmiedel_2018".

I have obtained the meta data with the following code:

```
library(tidyverse)
library(httr)
library(glue)
library(jsonlite)

max_pulled_rows <- 1000
URL <- glue("https://www.ebi.ac.uk/eqtl/api/v2/datasets/?size={max_pulled_rows}")

r <- GET(URL, accept_json())
status_code(r)

cont <- content(r, "text", encoding = "UTF-8")
datasets <- 
    fromJSON(cont) |>
    as_tibble()
```

And for the dataset in question I see the following:

```
| sample_group | tissue_label | condition_label |
|---------------|-------------|---------------|
| Treg_memory | Treg naive | naive |
| Treg_naive | Treg memory | naive |

```

There are both memory Tregs and naive Tregs in the data. The column `condition_label` will be "naive" for both because cells are not stimulated, I believe. But I wonder If `sample_group` or `tissue_label` are not switched for these datasets. 

Thank you,
Vitor

**Comment by kauralasoo** [comment]
Thanks for reporting! This should be fixed now!
