### ISSUE TITLE
GTEx-V7 and GTEx-V8 in eQTL-Catalogue

### ISSUE THREAD

**Issue by Shicheng-Guo** [eQTL-Catalogue/eQTL-Catalogue-resources#7]
I notice both GTEx-V7 and GTEx-V8 were mentioned in eQTL-Catalogue help page. 

https://www.ebi.ac.uk/eqtl/Studies/

Which one is exactly used in the web browses? Do we have any comparison between V7 and V8? What's the consistency? 

Thanks. 

Shicheng

**Comment by kauralasoo** [comment]
We now have two different versions of GTEx data in the eQTL Catalogue:
1. GTEx - Uniformly reprocessed GTEx v8 data with our workflows. This includes all four quantification methods.
2. GTEx_v8 -  official eQTL summary statistics released by GTEx. Only gene-level eQTL data is available, no transcript-level QTLs.

**Comment by Shicheng-Guo** [comment]
Thank you Kaur for the update!! Shicheng
